/**
 * generated by Xtext
 */
package at.ac.univie.swa.ase.example.validation;

import at.ac.univie.swa.ase.example.validation.AbstractPlaylistDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PlaylistDslValidator extends AbstractPlaylistDslValidator {
}
