/*
 * generated by Xtext
 */
package at.ac.univie.swa.ase2015.a9902268.task3.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import at.ac.univie.swa.ase2015.a9902268.task3.services.WikiMLGrammarAccess;

public class WikiMLParser extends AbstractContentAssistParser {
	
	@Inject
	private WikiMLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected at.ac.univie.swa.ase2015.a9902268.task3.ui.contentassist.antlr.internal.InternalWikiMLParser createParser() {
		at.ac.univie.swa.ase2015.a9902268.task3.ui.contentassist.antlr.internal.InternalWikiMLParser result = new at.ac.univie.swa.ase2015.a9902268.task3.ui.contentassist.antlr.internal.InternalWikiMLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractSectionAccess().getAlternatives(), "rule__AbstractSection__Alternatives");
					put(grammarAccess.getAbstractParagraphAccess().getAlternatives(), "rule__AbstractParagraph__Alternatives");
					put(grammarAccess.getWikiMLPageAccess().getGroup(), "rule__WikiMLPage__Group__0");
					put(grammarAccess.getPageTitleAccess().getGroup(), "rule__PageTitle__Group__0");
					put(grammarAccess.getSubSectionAccess().getGroup(), "rule__SubSection__Group__0");
					put(grammarAccess.getSubSubSectionAccess().getGroup(), "rule__SubSubSection__Group__0");
					put(grammarAccess.getSubSubSubSectionAccess().getGroup(), "rule__SubSubSubSection__Group__0");
					put(grammarAccess.getBoldParagraphAccess().getGroup(), "rule__BoldParagraph__Group__0");
					put(grammarAccess.getItalicParagraphAccess().getGroup(), "rule__ItalicParagraph__Group__0");
					put(grammarAccess.getWikiMLPageAccess().getTitleAssignment_0(), "rule__WikiMLPage__TitleAssignment_0");
					put(grammarAccess.getWikiMLPageAccess().getSectionAssignment_1(), "rule__WikiMLPage__SectionAssignment_1");
					put(grammarAccess.getPageTitleAccess().getNameAssignment_1(), "rule__PageTitle__NameAssignment_1");
					put(grammarAccess.getPageTitleAccess().getContentAssignment_3(), "rule__PageTitle__ContentAssignment_3");
					put(grammarAccess.getSubSectionAccess().getNameAssignment_1(), "rule__SubSection__NameAssignment_1");
					put(grammarAccess.getSubSectionAccess().getContentAssignment_3(), "rule__SubSection__ContentAssignment_3");
					put(grammarAccess.getSubSubSectionAccess().getNameAssignment_1(), "rule__SubSubSection__NameAssignment_1");
					put(grammarAccess.getSubSubSectionAccess().getContentAssignment_3(), "rule__SubSubSection__ContentAssignment_3");
					put(grammarAccess.getSubSubSubSectionAccess().getNameAssignment_1(), "rule__SubSubSubSection__NameAssignment_1");
					put(grammarAccess.getSubSubSubSectionAccess().getContentAssignment_3(), "rule__SubSubSubSection__ContentAssignment_3");
					put(grammarAccess.getNormalParagraphAccess().getNameAssignment(), "rule__NormalParagraph__NameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			at.ac.univie.swa.ase2015.a9902268.task3.ui.contentassist.antlr.internal.InternalWikiMLParser typedParser = (at.ac.univie.swa.ase2015.a9902268.task3.ui.contentassist.antlr.internal.InternalWikiMLParser) parser;
			typedParser.entryRuleWikiMLPage();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public WikiMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(WikiMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
