/*
* generated by Xtext
*/
package at.ac.univie.swa.ase.example;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PlaylistDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.ac.univie.swa.ase.example.ui.internal.PlaylistDslActivator.getInstance().getInjector("at.ac.univie.swa.ase.example.PlaylistDsl");
	}
	
}
