/**
 * generated by Xtext
 */
package at.ac.univie.swa.ase2014.a1276754.task3.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class MydslLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public MydslLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
