/**
 * generated by Xtext
 */
package at.ac.univie.swa.ase2014.a1276754.task3.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class MydslQuickfixProvider extends DefaultQuickfixProvider {
}
