SELECT 
XMLSERIALIZE( 
         XMLDOCUMENT( 
           XMLELEMENT( NAME "KURSE",
             XMLAGG(
               XMLFOREST( KURS.KURSNR AS "KURSNR", KURS.TITEL AS "KURSTITEL", FUEHRT_DURCH.ANGNR  AS "ANGNR")
             )
           ) 
         ) 
       AS CLOB VERSION '1.0' INCLUDING XMLDECLARATION) 

FROM KURS, FUEHRT_DURCH WHERE KURS.KURSNR = FUEHRT_DURCH.KURSNR