SELECT XMLSERIALIZE( 
         XMLDOCUMENT( 
           XMLELEMENT( NAME "TEILNEHMER", 
             XMLELEMENT( NAME "TNNR", TEILNEHMER.TNNR ), 
             XMLELEMENT( NAME "NAME", TEILNEHMER.NAME ), 
             XMLELEMENT( NAME "ORT", TEILNEHMER.ORT ) 
           ) 
         ) 
       AS CLOB VERSION '1.0' INCLUDING XMLDECLARATION)
FROM TEILNEHMER