/*
 * generated by Xtext
 */
package at.ac.univie.swa.ase.example.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.univie.swa.ase.example.ui.internal.PlaylistDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlaylistDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PlaylistDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PlaylistDslActivator.getInstance().getInjector(PlaylistDslActivator.AT_AC_UNIVIE_SWA_ASE_EXAMPLE_PLAYLISTDSL);
	}
	
}
