/*
* generated by Xtext
*/
package at.ac.univie.swa.ase2014.a1276754.task3.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.univie.swa.ase2014.a1276754.task3.services.MydslGrammarAccess;

public class MydslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MydslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.univie.swa.ase2014.a1276754.task3.parser.antlr.internal.InternalMydslParser createParser(XtextTokenStream stream) {
		return new at.ac.univie.swa.ase2014.a1276754.task3.parser.antlr.internal.InternalMydslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MydslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MydslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
