/**
 *
 * $Id$
 */
package at.ac.univie.swa.ase2015.a9902268.task2.Wikipedia.validation;

import at.ac.univie.swa.ase2015.a9902268.task2.Wikipedia.adminActions;
import at.ac.univie.swa.ase2015.a9902268.task2.Wikipedia.userType;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link at.ac.univie.swa.ase2015.a9902268.task2.Wikipedia.RegisteredUser}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RegisteredUserValidator {
	boolean validate();

	boolean validateUserName(String value);
	boolean validateRegistrationDateJD(BigInteger value);
	boolean validateRegisteredSinceDays(BigInteger value);
	boolean validateUserType(userType value);
	boolean validateAdminAction(adminActions value);
}
