/**
 *
 * $Id$
 */
package at.ac.univie.swa.ase2015.a9902268.task2.Wikipedia.validation;

import at.ac.univie.swa.ase2015.a9902268.task2.Wikipedia.Content;
import at.ac.univie.swa.ase2015.a9902268.task2.Wikipedia.User;

import java.math.BigDecimal;
import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link at.ac.univie.swa.ase2015.a9902268.task2.Wikipedia.Wikipedia}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WikipediaValidator {
	boolean validate();

	boolean validateCurrentDateJD(BigInteger value);
	boolean validateContent(EList<Content> value);
	boolean validateUser(EList<User> value);
	boolean validateAverageEditedPagesPerUser(BigDecimal value);
}
