/*
 * generated by Xtext
 */
package at.ac.univie.swa.ase2015.a9902268.task3.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WikiMLUiModule extends at.ac.univie.swa.ase2015.a9902268.task3.ui.AbstractWikiMLUiModule {
	public WikiMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
