/*
* generated by Xtext
*/
package at.ac.univie.swa.ase.example.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.univie.swa.ase.example.services.PlaylistDslGrammarAccess;

public class PlaylistDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PlaylistDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.univie.swa.ase.example.parser.antlr.internal.InternalPlaylistDslParser createParser(XtextTokenStream stream) {
		return new at.ac.univie.swa.ase.example.parser.antlr.internal.InternalPlaylistDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PlaylistDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PlaylistDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
