/*
* generated by Xtext
*/
package at.ac.univie.swa.ase2014.a1276754.task3;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MydslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.ac.univie.swa.ase2014.a1276754.task3.ui.internal.MydslActivator.getInstance().getInjector("at.ac.univie.swa.ase2014.a1276754.task3.Mydsl");
	}
	
}
