/*
 * generated by Xtext
 */
package at.ac.univie.swa.ase.example;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlaylistDslRuntimeModule extends at.ac.univie.swa.ase.example.AbstractPlaylistDslRuntimeModule {

}
