PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://univie.ac.at/cmoser/>
PREFIX team18: <http://univie.ac.at/cmoser/team18/>
PREFIX team4: <http://univie.ac.at/cmoser/team4/>
PREFIX team3: <http://univie.ac.at/cmoser/team3/>
PREFIX german: <http://univie.ac.at/cmoser/german/>

# Welche moeglichen alternativen Bezeichnungen gibt es fuer einen LV-Termin

SELECT *
FROM <ontology.ttl>
WHERE {
	  team18:time a ?synonym
}