/**
 * generated by Xtext
 */
package at.ac.univie.swa.ase2014.a1276754.task3.validation;

import at.ac.univie.swa.ase2014.a1276754.task3.validation.AbstractMydslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MydslValidator extends AbstractMydslValidator {
}
