<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aSE_Task2" nsURI="http://www.example.org/aSE_Task2" nsPrefix="aSE_Task2">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Account">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details value="self.beinhaltet->size() &lt;= 5"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Passwort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Land" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Abo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="30"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beinhaltet" lowerBound="1"
        upperBound="5" eType="#//Profile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leiht" upperBound="-1"
        eType="#//RentalMedia"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Media" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Titel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StreamingMedia" abstract="true" eSuperTypes="#//Media">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Groesse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RentalMedia" abstract="true" eSuperTypes="#//Media">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Anzahl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Profile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Passwort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writes" upperBound="-1"
        eType="#//Review" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Friend" upperBound="-1"
        eType="#//Profile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="streamt" upperBound="-1"
        eType="#//StreamingMedia"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MediaQeue" upperBound="-1"
        eType="#//StreamingMedia"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Recommandation" upperBound="-1"
        eType="#//Media"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Review">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="about" lowerBound="1" eType="#//Media"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Distributor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hat" lowerBound="1" eType="#//Media"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Movie" eSuperTypes="#//StreamingMedia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Regisseur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Music" eSuperTypes="#//StreamingMedia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Kuenstler" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TV_Series" eSuperTypes="#//StreamingMedia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Epsioden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="20"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RentalMovie" eSuperTypes="#//RentalMedia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Regisseur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RentalMusic" eSuperTypes="#//RentalMedia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Kuenstler" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RentalTV_Series" eSuperTypes="#//RentalMedia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Epsioden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="20"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newMedia" upperBound="-1"
        eType="#//Media" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newAccount" upperBound="-1"
        eType="#//Account" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
