SELECT DISTINCT COURSEIDATTRVAL.INTEGERVALUE AS COURSEID, 
                DURATION_MINATTR.INTEGERVALUE AS MAXAPPOINTMENTMIN,
                COURSENAMEVAL.STRINGVALUE AS COURSETITLE,
                COURSEWEEKHOURS.INTEGERVALUE AS COURSEWEEKHOURS,
                LECTURERNAMEVAL.STRINGVALUE AS LECTURERNAME
FROM EDGETABLE COURSE, 
     EDGETABLE GROUP, 
     EDGETABLE APPOINTMENT,
     EDGETABLE LECTURER, 
     EDGETABLE LECTURERNAMEATTR,
     EDGETABLE DURATION,
     EDGETABLE COURSEIDATTR,
     EDGETABLE COURSENAMEATTR,
     EDGETABLE COURSEWEEKHOURSATTR,
     EDGEVALUE_TABLE_INT DURATION_MINATTR,
     EDGEVALUE_TABLE_INT COURSEIDATTRVAL,
     EDGEVALUE_TABLE_INT COURSEWEEKHOURS,
     EDGEVALUE_TABLE_STRING COURSENAMEVAL,
     EDGEVALUE_TABLE_STRING LECTURERNAMEVAL
     
WHERE 
      -- get only starting from course tag
      COURSE.EDGENAME = 'course'
      -- join in the attribute @id
      AND COURSE.TARGETID = COURSEIDATTR.SOURCEID
      AND COURSEIDATTR.TARGETID = COURSEIDATTRVAL.INTEGERVALUEID      
      AND COURSEIDATTR.EDGENAME = '@id'
      -- join in the attribute @title
      AND COURSE.TARGETID = COURSENAMEATTR.SOURCEID
      AND COURSENAMEATTR.TARGETID = COURSENAMEVAL.STRINGVALUEID      
      AND COURSENAMEATTR.EDGENAME = '@title'
      -- join in the attribute @weekhours
      AND COURSE.TARGETID = COURSEWEEKHOURSATTR.SOURCEID
      AND COURSEWEEKHOURSATTR.TARGETID = COURSEWEEKHOURS.INTEGERVALUEID
      AND COURSEWEEKHOURSATTR.EDGENAME = '@weekhours'
      -- join in the group tag
      AND COURSE.TARGETID = GROUP.SOURCEID
      AND GROUP.EDGENAME = 'group'
      -- join in the appointment
      AND GROUP.TARGETID = APPOINTMENT.SOURCEID
      AND APPOINTMENT.EDGENAME = 'appointment'
      -- join in the attribute @duration_min
      AND APPOINTMENT.TARGETID = DURATION.SOURCEID
      AND DURATION.EDGENAME = '@duration_min'
      AND DURATION.TARGETID = DURATION_MINATTR.INTEGERVALUEID
      AND DURATION_MINATTR.INTEGERVALUE = (
         -- subquery to get the max value for the duration of an appointment
         SELECT MAX(EDGEVALUE_TABLE_INT.INTEGERVALUE) FROM EDGETABLE
                INNER JOIN EDGEVALUE_TABLE_INT
                ON EDGETABLE.TARGETID = EDGEVALUE_TABLE_INT.INTEGERVALUEID
                WHERE EDGETABLE.EDGENAME = '@duration_min')
      -- join in the lecturer
      AND GROUP.TARGETID = LECTURER.SOURCEID
      AND LECTURER.EDGENAME = 'lecturer'
      -- join in the attribute @name
      AND LECTURER.TARGETID = LECTURERNAMEATTR.SOURCEID
      AND LECTURERNAMEATTR.EDGENAME = '@name'
      AND LECTURERNAMEATTR.TARGETID = LECTURERNAMEVAL.STRINGVALUEID

;