/*
 * generated by Xtext
 */
package at.ac.univie.swa.ase.example.ui.contentassist

import at.ac.univie.swa.ase.example.ui.contentassist.AbstractPlaylistDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PlaylistDslProposalProvider extends AbstractPlaylistDslProposalProvider {
}
